// =================================================================================================
// Deploying the microservices
// =================================================================================================

=== Deploying the microservices

First, add the `ibm-charts` repository so that you may use the `ibm-open-liberty` chart.

```
helm repo add ibm-charts https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
```

// Setup Tiller for IKS
ifdef::use-iks[]
Set up Role Based Access Control (RBAC) to give Helm's tiller server admin access to your cluster. Deploy the service account and cluster role binding required for the tiller.

```
kubectl apply -f https://raw.githubusercontent.com/IBM-Cloud/kube-samples/master/rbac/serviceaccount-tiller.yaml
```

[source, role="no_copy"]
----
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created
----

Next, install the tiller to your cluster. Specify the service account that was created in the previous step.

```
helm init --service-account tiller
```
endif::[]

// Deploy to IKS
ifdef::use-iks[]
Use helm to deploy the `name` microservice.

```
helm install --name name-app \
    --set image.repository=registry.ng.bluemix.net/[your-namespace]/name \
    --set image.tag=1.0-SNAPSHOT \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty
```

Use helm to deploy the `ping` microservice.

```
helm install --name ping-app \
    --set image.repository=registry.ng.bluemix.net/[your-namespace]/ping \
    --set image.tag=1.0-SNAPSHOT \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty
```

The `--name` flag specifies the release name. This is the name that helm uses to identify this specific
deployment of your chart.
endif::[]

// Deploy to ICP
ifdef::use-icp[]
Use helm to deploy the `name` microservice.

```
helm install --name name-app \
    --set image.repository=mycluster.icp:8500/default/name \
    --set image.tag=1.0-SNAPSHOT \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty --tls
```

Use helm to deploy the `ping` microservice.

```
helm install --name ping-app \
    --set image.repository=mycluster.icp:8500/default/ping \
    --set image.tag=1.0-SNAPSHOT \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty --tls
```

The `--name` flag specifies the release name. This is the name that helm uses to identify this specific
deployment of your chart. The image repository and flag refers to the image you built for your microservices.
The `mycluster.icp:8500/default` prefix uses an image on your local cluster located in the `default` namespace.
endif::[]
