// =================================================================================================
// Pushing the images to a private docker registry
// =================================================================================================

=== Pushing the images to a private docker registry

Pushing the images a private registry will allow the cluster to create pods using your docker images. Since it's a private registry, only users with access to your cluster will have access to access these images.
ifdef::use-iks[]
The registry you will use is called IBM Cloud Container registry (ICR).
endif::[]
ifdef::use-icp[]
The registry you will use is included as part of your ICP installation.
endif::[]

// ICP Login
ifdef::use-icp[]
First, you will add your ICP instance to an insecure registry whitelist in your docker preferences. Go to your Docker Preferences and select the `Daemon` tab. If it's not checked, then check the `Experimental Features` box. Next, add an insecure registry to the list in the form `[hostname]:8500` where hostname is the hostname of your ICP instance. Click the `Apply & Restart` button and wait for the docker engine to start again.

Then, login to the docker registry from your command line and enter your user name and password when prompted.

```
docker login [hostname]:8500
```

[source, role="no_copy"]
----
Username: your_username
Password: your_password
WARNING! Your password will be stored unencrypted in ~/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
----
endif::[]

// ICR Login
ifdef::use-iks[]
Install the container registry plugin.

```
ibmcloud plugin install container-registry -r Bluemix
```

Use the container registry plugin to create a namespace for your container images.
The namespace must be unique, so choose something relevant that you'll remember for the duration of the guide.

```
ibmcloud cr namespace-add [your-namespace]
```

Use the plugin again to login to the docker registry.

```
ibmcloud cr login
```
endif::[]

// Tagging images
Next, you need to tag your docker images with the relevant data about your registry.

ifdef::use-iks[]
```
docker tag name:1.0-SNAPSHOT registry.ng.bluemix.net/[your-namespace]/name:1.0-SNAPSHOT
docker tag ping:1.0-SNAPSHOT registry.ng.bluemix.net/[your-namespace]/ping:1.0-SNAPSHOT
```
endif::[]
ifdef::use-icp[]
```
docker tag name:1.0-SNAPSHOT [hostname]:8500/default/name:1.0-SNAPSHOT
docker tag ping:1.0-SNAPSHOT [hostname]:8500/default/ping:1.0-SNAPSHOT
```
endif::[]

// Pushing images
Finally, push your images to the registry.

ifdef::use-iks[]
```
docker push registry.ng.bluemix.net/[your-namespace]/name:1.0-SNAPSHOT
docker push registry.ng.bluemix.net/[your-namespace]/ping:1.0-SNAPSHOT
```
endif::[]
ifdef::use-icp[]
```
docker push [hostname]:8500/default/name:1.0-SNAPSHOT
docker push [hostname]:8500/default/ping:1.0-SNAPSHOT
```
endif::[]
