// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: ibm-cloud-intro
:page-layout: guide
:page-duration: 25 minutes
:page-releasedate: 2018-10-05
:page-description: Explore how to deploy microservices to IBM Cloud Private and manage your cluster.
:page-tags: ['microservices', 'Kubernetes', 'Docker', 'containers', 'kubectl', 'ICP', 'IBM Cloud Private']
:page-permalink: /guides/{projectid}
:page-related-guides: ['kubernetes-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: IBM Cloud Private tutorial
:page-seo-description: How to deploy microservices to IBM Cloud Private and manage your cluster
= Deploying microservices to IBM Cloud Private

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Deploy microservices in Open Liberty Docker containers to IBM Cloud.

:minikube-ip: 192.168.99.100
:kube: Kubernetes
:hashtag: #
:win: WINDOWS
:mac: MAC
:linux: LINUX
:name-api: http://[hostname]:31000/api/name
:ping-api: http://[hostname]:32000/api/ping


// =================================================================================================
// What is {kube}
// =================================================================================================

== IBM Cloud

=== What is IBM Cloud Private (ICP)?

IBM Cloud Private is a {kube} platform that provides an on-premises cloud solution. It has many useful features for your cloud needs. The main feature it provides is a {kube} cluster. It works just like any {kube} cluster and can be manipulated with `kubectl`. Another useful feature it provides is a private docker registry so that you don't need to use something like https://hub.docker.com/[Docker Hub]. Some other capabilities it provides include a dashboard and a web interface to deploy helm charts.

=== What is IBM Cloud Kubernetes Service (IKS)?

IKS is a service offered as part of IBM's public cloud offerings. It provides a managed {kube} cluster that you may deploy your microservices to. You will use it in conjunction with IBM Cloud Container Registry.

// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

You will learn how to deploy two microservices in Open Liberty containers to a {kube}
cluster on IBM Cloud. You will use `helm` to deploy these microservices using IBM's
Open Liberty Helm charts.

The two microservices you'll deploy are called `name` and `ping`. The `name` microservice
displays a brief greeting and the name of the
container it's running in. This message makes it easy to differentiate it from its other replicas. The `ping` microservice
pings the {kube} Service that encapsulates the `name` pods. This communication demonstrates
how communication can be established between pods inside a cluster.

// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisites

First, you will need Docker to build your containers, refer to the https://docs.docker.com/install/[official Docker documentation] to install Docker.

You will also need to install the https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl] cli tool.

Finally, you'll need to have access to an IBM Cloud Private instance that you may use to follow the guide. This is only necessary if you
are following the ICP instructions. You do not need an ICP instance to follow the IKS instructions.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.


// =================================================================================================
// Connecting to your ICP cluster
// =================================================================================================

== Connecting to your ICP cluster

=== Installing cloudctl

1. First, login and navigate to your ICP dashboard.
2. Click the icon located at the upper left of the page to expand the menu.
3. Click `Command Line Tools > Cloud Private CLI` to navigate to the `IBM Cloud Private CLI` page.
4. Click `Install IBM Cloud Private CLI and plug-ins` and follow the instructions to download the `cloudctl` tool.

****
[system]#*{linux} | {mac}*#

Move and rename the downloaded file to `/usr/local/bin/cloudctl` then make it executable.

```
sudo mv `ls cloudctl-*` /usr/local/bin/cloudctl
sudo chmod +x /usr/local/bin/cloudctl
```

[system]#*{win}*#

Create a directory called `cloudctl-bin` under your user directory and add it to your `PATH` environment variable.

```
mkdir %systemdrive%%userprofile%\cloudctl-bin
set PATH=%PATH%;%systemdrive%%userprofile%\cloudctl-bin
```

Next, move the file you downloaded into the `cloudctl-bin` directory and rename the file to `cloudctl.exe`.
****

=== Installing helm

Click `Install Helm` on the same page where you downloaded `cloudctl`. Follow the instructions to download `helm`.

****
[system]#*{linux} | {mac}*#

Use the following commands to extract the archive and move the helm binary to `/usr/local/bin/helm` and then make it executable.

```
mkdir helm
tar -zxf helm-* -C helm/
sudo mv helm/`ls helm`/helm /usr/local/bin/helm
sudo chmod +x /usr/local/bin/helm
```

[system]#*{win}*#

Create a directory called `helm-cli` under your user directory and extract the contents of the file
you downloaded to this directory. Use the following commands to add `helm` to your path.

Create a directory called `helm-cli` under your user directory and add it to your `PATH` environment variable.

```
mkdir %systemdrive%%userprofile%\helm-cli\windows-amd64
set PATH=%PATH%;%systemdrive%%userprofile%\helm-cli\windows-amd64
```

Next, extract the file you downloaded into the `helm-cli` directory.
****

=== Connecting kubectl and helm to ICP

Connect the `kubectl` cli tool to your cluster by logging in to the cluster, replace `[hostname]` and `[port]` as appropriate with the values for your ICP instance.

```
cloudctl login -a https://[hostname]:[port]  --skip-ssl-validation
```

When prompted, enter your username and password. Then, select the cluster account. Finally, ensure to select the `default` namespace.

----
Username> enter_your_username	

Password> enter_your_password
Authenticating...
OK

Select an account:
1. mycluster Account (id-mycluster-account)
Enter a number> 1
Targeted account mycluster Account (id-mycluster-account)

Select a namespace:
1. cert-manager
2. default
3. ibmcom
4. istio-system
5. kube-public
6. kube-system
7. platform
8. services
Enter a number> 2
Targeted namespace default

Configuring kubectl ...
Property "clusters.mycluster" unset.
Property "users.mycluster-user" unset.
Property "contexts.mycluster-context" unset.
Cluster "mycluster" set.
User "mycluster-user" set.
Context "mycluster-context" created.
Switched to context "mycluster-context".
OK

Configuring helm: ~/.helm
OK
----

Verify that you're connected to the cluster by checking the cluster's nodes.

```
kubectl get nodes
```

----
NAME           STATUS    ROLES                          AGE       VERSION
192.168.0.15   Ready     worker                         10d       v1.11.1+icp-ee
192.168.0.10   Ready     worker                         10d       v1.11.1+icp-ee
192.168.0.5    Ready     etcd,management,master,proxy   10d       v1.11.1+icp-ee
----

== Setting up an IBM Cloud Kubernetes Service (IKS) instance

=== Installing command line tools for IBM Cloud

Use the following command to download and install everything you will need to interact with IBM Cloud.
Running this script will install https://console.bluemix.net/docs/cli/index.html#overview[several tools]
that will be useful for interacting with IBM Cloud. It will install the `ibmcloud`, `kubectl`, `helm`,
and `curl` tools which are needed to complete this guide.

****
[system]#*{linux} | {mac}*#

```
curl -sL https://ibm.biz/idt-installer | bash
```

[system]#*{win}*#

Open PowerShell as an administrator and run the following command.

```
Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('http://ibm.biz/idt-win-installer')
```
****

Once the script has finished running, login with the command line to IBM Cloud.

```
ibmcloud login
```

If you are logging in with organization credentials, you may need to pass in the `--sso` flag
to get a one time code for single sign-on. Follow the instructions given on the prompt and in
your web browser to complete the login process.

```
ibmcloud login --sso
```

=== Provisioning a cluster

Use the following command to provision a cluster.

// ```
// ibmcloud ks cluster-create \
//     --zone dal10 \
//     --machine-type b2c.4x16 \
//     --hardware <shared_or_dedicated> \
//     --public-vlan <public_VLAN_ID> \
//     --private-vlan <private_VLAN_ID> \
//     --workers 3 \
//     --name <cluster_name> \
//     --kube-version <major.minor.patch>
// ```

```
ibmcloud ks cluster-create --name guide-cluster
```

This command provisions a free cluster that will expire in a month if you do not delete it.

----
The 'machine-type' flag was not specified. So a free cluster will be created.
Creating cluster...
OK
----

Check the current status of your cluster.

```
ibmcloud ks clusters
```

----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   deploying   4 minutes ago   1         Dallas     1.10.11_1536   default 
----

----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   pending     19 minutes ago   1         Dallas     1.10.11_1536   default 
----

Wait until the `State` of your cluster is `normal` before proceeding with the guide. This may take a while for IKS to prepare your cluster.

----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   normal      4 hours ago     1           Dallas     1.10.11_1536   default 
----


Once your cluster is ready, connect `kubectl` to the cluster.
****
[system]#*{linux} | {mac}*#

```
eval $(ibmcloud ks cluster-config --export guide-cluster)
```
[system]#*{win}*#

```
ibmcloud ks cluster-config --export guide-cluster > tmp-set-cluster.cmd
call tmp-set-cluster.cmd
del tmp-set-cluster.cmd
```
****

Verify that you're connected to the cluster by checking the cluster's nodes.

```
kubectl get nodes
```

----
NAME           STATUS    ROLES     AGE       VERSION
10.70.200.73   Ready     <none>    1h        v1.10.11+IKS
----

// =================================================================================================
// Building and containerizing the microservices
// =================================================================================================

== Building and containerizing the microservices

The first step of deploying to {kube} is to build your microservices and containerize them with Docker.

The starting Java project, which you can find in the `start` directory, is a multi-module Maven
project. It's made up of the `name` and `ping` microservices. Each microservice resides in its own directory,
`start/name` and `start/ping`. Each of these directories also contains a Dockerfile, which is necessary
for building Docker images. If you're unfamiliar with Dockerfiles, check out the
https://openliberty.io/guides/docker.html[Using Docker containers to develop microservices] guide,
which covers Dockerfiles in depth.

If you're familiar with Maven and Docker, you might be tempted to run a Maven build first and then
use the `.war` file to build a Docker image. While it's by no means a wrong
approach, we've setup the projects such that this process is automated
as a part of a single Maven build. It's created by using the `dockerfile-maven` plug-in. The plugin automatically
picks up the Dockerfile located in the same directory as its POM file and builds a Docker image from it.
If you're using Docker for Windows ensure that, on the Docker for Windows _General Setting_ page, the option is set to `Expose daemon on tcp://localhost:2375 without TLS`. This configuration is required by the `dockerfile-maven` part of the build.

Navigate to the `start` directory and run the following command:

```
mvn package
```

The `package` goal automatically starts the `dockerfile-maven:build` goal. It runs during the
`package` phase. This goal builds a Docker image from the Dockerfile located in the same directory
as the POM file.

During the build, you'll see various Docker messages describing what images are being downloaded and
built. When the build finishes, run the following command to list all local Docker images:

```
docker images
```

Verify that the `name:1.0-SNAPSHOT` and `ping:1.0-SNAPSHOT` images are listed among them, for example:

[source, role="no_copy"]
----
REPOSITORY                                                       TAG
ping                                                             1.0-SNAPSHOT
name                                                             1.0-SNAPSHOT
open-liberty                                                     latest
----

If you don't see the `name:1.0-SNAPSHOT` and `ping:1.0-SNAPSHOT` images, then check the Maven
build log for any potential errors.

// =================================================================================================
// Pushing the images to a private docker registry
// =================================================================================================

== Pushing the images to a private docker registry

Pushing the images a private registry will allow the cluster to create pods using your docker images. Since it's a private registry, only users with access to your cluster will have access to access these images.

=== Pushing to the ICP docker registry

First, you will add your ICP instance to an insecure registry whitelist in your docker preferences. Go to your Docker Preferences and select the `Daemon` tab. If it's not checked, then check the `Experimental Features` box. Next, add an insecure registry to the list in the form `[hostname]:8500` where hostname is the hostname of your ICP instance. Click the `Apply & Restart` button and wait for the docker engine to start again.

Then, login to the docker registry from your command line and enter your user name and password when prompted.

```
docker login [hostname]:8500
```

[source, role="no_copy"]
----
Username: your_username
Password: your_password
WARNING! Your password will be stored unencrypted in ~/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
----

Next, you need to tag your docker image with the relevant data about your registry.

```
docker tag name:1.0-SNAPSHOT [hostname]:8500/default/name:1.0-SNAPSHOT
docker tag ping:1.0-SNAPSHOT [hostname]:8500/default/ping:1.0-SNAPSHOT
```

Then, push your images to the private registry.

```
docker push [hostname]:8500/default/name:1.0-SNAPSHOT
docker push [hostname]:8500/default/ping:1.0-SNAPSHOT
```

=== Pushing to an IBM Cloud container registry

Install the container registry plugin.

```
ibmcloud plugin install container-registry -r Bluemix
```

Use the container registry plugin to create a namespace for your container images.
The namespace must be unique, so choose something relevant that you'll remember for the duration of the guide.

```
ibmcloud cr namespace-add [your-namespace]
```

Use the plugin again to login to the docker registry.

```
ibmcloud cr login
```

Next, you need to tag your docker images with the relevant data about your registry.

```
docker tag name:1.0-SNAPSHOT registry.ng.bluemix.net/[your-namespace]/name:1.0-SNAPSHOT
docker tag ping:1.0-SNAPSHOT registry.ng.bluemix.net/[your-namespace]/ping:1.0-SNAPSHOT
```

Finally, push your images to the registry.

```
docker push registry.ng.bluemix.net/[your-namespace]/name:1.0-SNAPSHOT
docker push registry.ng.bluemix.net/[your-namespace]/ping:1.0-SNAPSHOT
```

// =================================================================================================
// Deploying the microservices
// =================================================================================================

== Deploying the microservices

Add the `ibm-charts` repository so that you may use the `ibm-open-liberty` chart.

```
helm repo add ibm-charts https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
```

=== Deploying to IBM Cloud Private

Use helm to deploy the `name` microservice.

```
helm install --name name-app \
    --set image.repository=mycluster.icp:8500/default/name \
    --set image.tag=1.0-SNAPSHOT \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty --tls
```

Use helm to deploy the `ping` microservice.

```
helm install --name ping-app \
    --set image.repository=mycluster.icp:8500/default/ping \
    --set image.tag=1.0-SNAPSHOT \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty --tls
```

The `--name` flag specifies the release name. This is the name that helm uses to identify this specific
deployment of your chart. The image repository and flag refers to the image you built for your microservices.
The `mycluster.icp:8500/default` prefix uses an image on your local cluster located in the `default` namespace.

=== Deploying to IBM Cloud Kubernetes Service

First, setup RBAC to give Helm's tiller server admin access to your cluster. Deploy the service account and cluster role binding required for the tiller.

```
kubectl apply -f https://raw.githubusercontent.com/IBM-Cloud/kube-samples/master/rbac/serviceaccount-tiller.yaml
```

[source, role="no_copy"]
----
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created
----

Next, install the tiller to your cluster. Specify the service account that was created in the previous step.

```
helm init --service-account tiller
```

Use helm to deploy the `name` microservice.

```
helm install --name name-app \
    --set image.repository=registry.ng.bluemix.net/[your-namespace]/name \
    --set image.tag=1.0-SNAPSHOT \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty
```

Use helm to deploy the `ping` microservice.

```
helm install --name ping-app \
    --set image.repository=registry.ng.bluemix.net/[your-namespace]/ping \
    --set image.tag=1.0-SNAPSHOT \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty
```

The `--name` flag specifies the release name. This is the name that helm uses to identify this specific
deployment of your chart.

=== Making requests to the microservices

Get the ip address of the cluster.

****
[system]#*ICP*#

```
kubectl get nodes -l proxy=true -o jsonpath="{.items[0].status.addresses[?(@.type==\"Hostname\")].address}"
```

[system]#*IKS*#

```
ibmcloud ks workers $(kubectl config current-context)
```
****

Get the node port of the `name` microservice.

```
kubectl get service name-app-ibm-open-libert -o jsonpath="{.spec.ports[0].nodePort}"
```

Get the node port of the `ping` microservice.

```
kubectl get service ping-app-ibm-open-libert -o jsonpath="{.spec.ports[0].nodePort}"
```

Take note of the ip address and ports. They are required to make the HTTP requests.

Make a request to the `name` microservice.

```
curl http://[ip-address]:[nameNodePort]/api/name
```

```
curl http://[ip-address]:[pingNodePort]/api/ping/name-app-ibm-open-libert
```

// =================================================================================================
// Testing microservices that are running on {kube}
// =================================================================================================

== Testing microservices that are running on ICP

A few tests are included for you to test the basic functionality of the microservices. If a test failure
occurs, then you might have introduced a bug into the code. To run the tests, wait for all pods to be
in the ready state before proceeding further. The default properties defined in the `pom.xml` are:

[cols="15, 100", options="header"]
|===
| *Property*        | *Description*
| cluster.ip        | IP or hostname for your cluster
| name.kube.service | Name of the {kube} Service wrapping the `name` pods, `name-service` by default.
| name.node.port    | The NodePort of the {kube} Service `name-service`, 31000 by default.
| ping.node.port    | The NodePort of the {kube} Service `ping-service`, 32000 by default.
|===

Navigate back to the `start` directory.

Run the integration tests against your cluster:

```
mvn verify \
    -Ddockerfile.skip=true \
    -Dcluster.ip=[ip-address] \
    -Dname.node.port=`kubectl get service name-app-ibm-open-libert -o jsonpath="{.spec.ports[0].nodePort}"` \
    -Dping.node.port=`kubectl get service ping-app-ibm-open-libert -o jsonpath="{.spec.ports[0].nodePort}"` \
    -Dname.kube.service=name-app-ibm-open-libert
```

The `dockerfile.skip` parameter is set to `true` in order to skip building a new Docker image.

If the tests pass, you'll see an output similar to the following for each service respectively:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.name.NameEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.673 sec - in it.io.openliberty.guides.name.NameEndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.ping.PingEndpointTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.222 sec - in it.io.openliberty.guides.ping.PingEndpointTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----


// =================================================================================================
// Tear Down
// =================================================================================================

== Tearing down the environment

When you no longer need your deployed microservices, you can delete them with the following helm commands:

```
helm delete --purge name-app
helm delete --purge ping-app
```

=== Logging out of ICP

Logout of your docker registry.

```
docker logout [hostname]:8500
```

Logout of your ICP cluster.

```
cloudctl logout
```

=== Tearing down IKS

Logout of your docker registry.

```
docker logout registry.ng.bluemix.net
```

Remove your IKS cluster.

```
ibmcloud ks cluster-rm guide-cluster
```

Logout of the `ibmcloud` command line tool.

```
ibmcloud logout
```

// =================================================================================================
// finish
// =================================================================================================

== Great work! You're done!

You have just deployed two microservices to IBM Cloud. You have learned to use Helm to install your microservices
on a {kube} cluster using IBM's helm chart for Open Liberty.

// Include the below from the guides-common repo to tell users how they can contribute to the guide
include::{common-includes}/finish.adoc[]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
