// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: cloud-ibm
:page-layout: guide-multipane
:page-duration: 4 hours
:page-releasedate: 2018-10-05
:page-description: Explore how to deploy microservices to IBM Cloud Private and manage your cluster.
:page-tags: ['Kubernetes', 'Docker']
:page-permalink: /guides/{projectid}
:page-related-guides: ['kubernetes-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: IBM Cloud tutorial
:page-seo-description: How to deploy microservices to IBM Cloud
:guide-author: Open Liberty
= Deploying microservices to IBM Cloud

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Deploy microservices in Open Liberty Docker containers to IBM Cloud.

:minikube-ip: 192.168.99.100
:kube: Kubernetes
:hashtag: #
:win: WINDOWS
:mac: MAC
:linux: LINUX
:name-api: http://[hostname]:31000/api/name
:ping-api: http://[hostname]:32000/api/ping


// =================================================================================================
// What is {kube}
// =================================================================================================

== Why use cloud-hosted Kubernetes services?

Single node {kube} clusters such as Minikube and Docker Desktop are great for testing your microservices locally. In production, you'll want to use something more robust. Various clouds offer solutions for running your workloads in a {kube} cluster. Using cloud infrastructure allows you to focus on developing your microservices rather than worrying about details related to the servers you'll deploy them to. 

IBM Cloud offers a managed Kubernetes service called IBM Cloud Kubernetes Service (IKS). IKS is a service offered as part of IBM's public cloud offerings. It provides a managed {kube} cluster that you may deploy your microservices to. You will use it in conjunction with IBM Cloud Container Registry.

// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

You will learn how to deploy two microservices in Open Liberty containers to a {kube}
cluster on IBM Cloud. You will use `helm` to deploy these microservices using IBM's
Open Liberty Helm charts.

The two microservices you'll deploy are called `name` and `ping`. The `name` microservice
displays a brief greeting and the name of the
container it's running in. This message makes it easy to differentiate it from its other replicas. The `ping` microservice
pings the {kube} Service that encapsulates the `name` pods. This communication demonstrates
how communication can be established between pods inside a cluster.

// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisites

You will need Docker to build your containers, refer to the https://docs.docker.com/install/[official Docker documentation] to install Docker.

// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.

== Deploying microservices to IBM Cloud Kubernetes Service (IKS)

=== Installing command line tools for IBM Cloud

Use the following command to download and install everything you will need to interact with IBM Cloud.
Running this script will install https://console.bluemix.net/docs/cli/index.html#overview[several tools]
that will be useful for interacting with IBM Cloud. It will install the `ibmcloud`, `kubectl`, `helm`,
and `curl` tools which are needed to complete this guide.

****
[system]#*{linux} | {mac}*#

[role=command]
```
curl -sL https://ibm.biz/idt-installer | bash
```

[system]#*{win}*#

Open PowerShell as an administrator and run the following command.

[role=command]
```
Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('http://ibm.biz/idt-win-installer')
```
****

Once the script has finished running, login with the command line to IBM Cloud.

[role=command]
```
ibmcloud login
```

If you're logging in with organization credentials, you may need to pass in the `--sso` flag
to get a one time code for single sign-on. Follow the instructions given on the prompt and in
your web browser to complete the login process.

[role=command]
```
ibmcloud login --sso
```

=== Provisioning a cluster

Use the following command to provision a cluster.

// ```
// ibmcloud ks cluster-create \
//     --zone dal10 \
//     --machine-type b2c.4x16 \
//     --hardware <shared_or_dedicated> \
//     --public-vlan <public_VLAN_ID> \
//     --private-vlan <private_VLAN_ID> \
//     --workers 3 \
//     --name <cluster_name> \
//     --kube-version <major.minor.patch>
// ```

[role=command]
```
ibmcloud ks cluster-create --name guide-cluster
```

This command provisions a free cluster that will expire in a month if you do not delete it.

----
The 'machine-type' flag was not specified. So a free cluster will be created.
Creating cluster...
OK
----

Check the current status of your cluster.

[role=command]
```
ibmcloud ks clusters
```

----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   deploying   4 minutes ago   1         Dallas     1.10.11_1536   default 
----

----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   pending     19 minutes ago   1         Dallas     1.10.11_1536   default 
----

Wait until the `State` of your cluster is `normal` before proceeding with the guide. This may take a while for IKS to prepare your cluster.

----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   normal      4 hours ago     1           Dallas     1.10.11_1536   default 
----


Once your cluster is ready, connect `kubectl` to the cluster.
****
[system]#*{linux} | {mac}*#

```
eval $(ibmcloud ks cluster-config --export guide-cluster)
```
[system]#*{win}*#

```
ibmcloud ks cluster-config --export guide-cluster > tmp-set-cluster.cmd
call tmp-set-cluster.cmd
del tmp-set-cluster.cmd
```
****

Verify that you're connected to the cluster by checking the cluster's nodes.

[role=command]
```
kubectl get nodes
```

----
NAME           STATUS    ROLES     AGE       VERSION
10.70.200.73   Ready     <none>    1h        v1.10.11+IKS
----

// =================================================================================================
// Building and containerizing the microservices
// =================================================================================================

=== Building and containerizing the microservices

The first step of deploying to {kube} is to build your microservices and containerize them with Docker.

The starting Java project, which you can find in the `start` directory, is a multi-module Maven
project. It's made up of the `name` and `ping` microservices. Each microservice resides in its own directory,
`start/name` and `start/ping`. Each of these directories also contains a Dockerfile, which is necessary
for building Docker images. If you're unfamiliar with Dockerfiles, check out the
https://openliberty.io/guides/docker.html[Using Docker containers to develop microservices] guide.
It covers Dockerfiles in depth.

If you're familiar with Maven and Docker, you might be tempted to run a Maven build first and then
use the `.war` file to build a Docker image. While it's by no means a wrong
approach, we've setup the projects such that this process is automated
as a part of a single Maven build. It's created by using the `dockerfile-maven` plug-in. The plug-in automatically
picks up the Dockerfile located in the same directory as its POM file and builds a Docker image from it.
If you're using Docker for Windows ensure that, on the Docker for Windows _General Setting_ page, the option is set to `Expose daemon on tcp://localhost:2375 without TLS`. This configuration is required by the `dockerfile-maven` part of the build.

Navigate to the `start` directory and run the following command:

[role=command]
```
mvn package
```

The `package` goal automatically starts the `dockerfile-maven:build` goal. It runs during the
`package` phase. This goal builds a Docker image from the Dockerfile located in the same directory
as the POM file.

During the build, you'll see various Docker messages describing what images are being downloaded and
built. When the build finishes, run the following command to list all local Docker images:

[role=command]
```
docker images
```

Verify that the `name:1.0-SNAPSHOT` and `ping:1.0-SNAPSHOT` images are listed among them, for example:

[source, role="no_copy"]
----
REPOSITORY               TAG
ping                     1.0-SNAPSHOT
name                     1.0-SNAPSHOT
open-liberty             latest
----

If you don't see the `name:1.0-SNAPSHOT` and `ping:1.0-SNAPSHOT` images, then check the Maven
build log for any potential errors.

// =================================================================================================
// Pushing the images to a private docker registry
// =================================================================================================

=== Pushing the images to a private docker registry

Pushing the images a private registry will allow the cluster to create pods using your docker images. Since it's a private registry, only users with access to your cluster will have access to access these images.

The registry you will use is called IBM Cloud Container registry (ICR).

// ICR Login
Install the container registry plugin.

[role=command]
```
ibmcloud plugin install container-registry -r Bluemix
```

Use the container registry plugin to create a namespace for your container images.
The namespace must be unique, so choose something relevant that you'll remember for the duration of the guide.

[role=command]
```
ibmcloud cr namespace-add [your-namespace]
```

Use the plugin again to login to the docker registry.

[role=command]
```
ibmcloud cr login
```

// Tagging images
Next, you need to tag your docker images with the relevant data about your registry.

[role=command]
```
docker tag name:1.0-SNAPSHOT registry.ng.bluemix.net/[your-namespace]/name:1.0-SNAPSHOT
docker tag ping:1.0-SNAPSHOT registry.ng.bluemix.net/[your-namespace]/ping:1.0-SNAPSHOT
```

// Pushing images
Finally, push your images to the registry.

[role=command]
```
docker push registry.ng.bluemix.net/[your-namespace]/name:1.0-SNAPSHOT
docker push registry.ng.bluemix.net/[your-namespace]/ping:1.0-SNAPSHOT
```

// =================================================================================================
// Deploying the microservices
// =================================================================================================

=== Deploying the microservices

First, add the `ibm-charts` repository so that you may use the `ibm-open-liberty` chart.

[role=command]
```
helm repo add ibm-charts https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
```

// Setup Tiller for IKS
Set up Role Based Access Control (RBAC) to give Helm's tiller server admin access to your cluster. Deploy the service account and cluster role binding required for the tiller.

[role=command]
```
kubectl apply -f https://raw.githubusercontent.com/IBM-Cloud/kube-samples/master/rbac/serviceaccount-tiller.yaml
```

[source, role="no_copy"]
----
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created
----

Next, install the tiller to your cluster. Specify the service account that was created in the previous step.

[role=command]
```
helm init --service-account tiller
```

// Deploy to IKS
Use helm to deploy the `name` microservice.

[role=command]
```
helm install --name name-app \
    --set image.repository=registry.ng.bluemix.net/[your-namespace]/name \
    --set image.tag=1.0-SNAPSHOT \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty
```

Use helm to deploy the `ping` microservice.

[role=command]
```
helm install --name ping-app \
    --set image.repository=registry.ng.bluemix.net/[your-namespace]/ping \
    --set image.tag=1.0-SNAPSHOT \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty
```

The `--name` flag specifies the release name. This is the name that helm uses to identify this specific
deployment of your chart.

=== Making requests to the microservices

Get the ip address of the cluster.

[role=command]
```
ibmcloud ks workers $(kubectl config current-context)
```

Get the node port of the `name` microservice.

[role=command]
```
kubectl get service name-app-ibm-open-libert -o jsonpath="{.spec.ports[0].nodePort}"
```

Get the node port of the `ping` microservice.

[role=command]
```
kubectl get service ping-app-ibm-open-libert -o jsonpath="{.spec.ports[0].nodePort}"
```

Take note of the ip address and ports. They are required to make the HTTP requests.

Make a request to the `name` microservice.

[role=command]
```
curl http://[ip-address]:[nameNodePort]/api/name
```

Make a request to the `ping` microservice.

[role=command]
```
curl http://[ip-address]:[pingNodePort]/api/ping/name-app-ibm-open-libert
```

// =================================================================================================
// Testing microservices that are running on IBM Cloud
// =================================================================================================

== Testing microservices that are running on IBM Cloud

A few tests are included for you to test the basic functionality of the microservices. If a test failure
occurs, then you might have introduced a bug into the code. To run the tests, wait for all pods to be
in the ready state before proceeding further. The default properties defined in the `pom.xml` are:

[cols="15, 100", options="header"]
|===
| *Property*        | *Description*
| cluster.ip        | IP or hostname for your cluster
| name.kube.service | Name of the {kube} Service wrapping the `name` pods, `name-service` by default.
| name.node.port    | The NodePort of the {kube} Service `name-service`, 31000 by default.
| ping.node.port    | The NodePort of the {kube} Service `ping-service`, 32000 by default.
|===

Navigate back to the `start` directory.

Run the integration tests against your cluster:

[role=command]
```
mvn verify \
    -Ddockerfile.skip=true \
    -Dcluster.ip=[ip-address] \
    -Dname.node.port=`kubectl get service name-app-ibm-open-libert -o jsonpath="{.spec.ports[0].nodePort}"` \
    -Dping.node.port=`kubectl get service ping-app-ibm-open-libert -o jsonpath="{.spec.ports[0].nodePort}"` \
    -Dname.kube.service=name-app-ibm-open-libert
```

The `dockerfile.skip` parameter is set to `true` in order to skip building a new Docker image.

If the tests pass, you'll see an output similar to the following for each service respectively:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.name.NameEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.673 sec - in it.io.openliberty.guides.name.NameEndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.ping.PingEndpointTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.222 sec - in it.io.openliberty.guides.ping.PingEndpointTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

// =================================================================================================
// Tear Down
// =================================================================================================

=== Tearing down the environment

When you no longer need your deployed microservices, you can delete them with the following helm commands:

[role=command]
```
helm delete --purge name-app
helm delete --purge ping-app
```

Logout of your docker registry.

[role=command]
```
docker logout registry.ng.bluemix.net
```

Remove your IKS cluster.

[role=command]
```
ibmcloud ks cluster-rm guide-cluster
```

Logout of the `ibmcloud` command line tool.

[role=command]
```
ibmcloud logout
```

== IBM Cloud Private

Some may feel that public clouds are not secure enough for their workloads, or maybe you are under specific scrutiny that requires you to have on-premises solutions. If this is the case, then private clouds may be more suitable for your needs.

https://www.ibm.com/cloud/private[IBM Cloud Private] (ICP) is an on-premises {kube} platform. A private cloud may be a more attractive option to those who need the security of having their services running on infrastructure controlled by them. While someone will still need to maintain this infrastructure, a private cloud still provides benefit to developers such that they don't need to think about infrastructure. {kube} acts as an abstraction of the infrastructure so the developers can request what they need and it is the responsibility of the infrastructure's maintainers to provide the necessary resources.

Deploying microservices to ICP is a similar process as deploying to IKS. The main differences you will notice are in the setup process and how you tag your Docker images. With respect to the setup process, you will not need to run `helm init` or deploy the cluster role binding and service account to your cluster because ICP has Helm's Tiller setup for you out of the box. When you tag a Docker image, you must tag the image with the registry as a prefix to your image name. This prefix is how Docker knows which registry to push your images to. You can learn more about deploying microservices to ICP by following an https://www.ibm.com/cloud/garage/demo/try-private-cloud-install-an-app[interactive guided demo].

// =================================================================================================
// finish
// =================================================================================================

== Great work! You're done!

You have just deployed two microservices to IBM Cloud. You have learned to use Helm to install your microservices
on a {kube} cluster using IBM's helm chart for Open Liberty.

// Multipane
include::https://raw.githubusercontent.com/OpenLiberty/guides-common/multipane/attribution.adoc[subs="attributes"]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
