// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2018, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: cloud-ibm
:page-layout: guide
:page-duration: 1 hour
:page-releasedate: 2018-10-05
:page-description: Explore how to deploy microservices to IBM Cloud Private and manage your cluster.
:page-tags: ['kubernetes', 'docker']
:page-permalink: /guides/{projectid}
:page-related-guides: ['kubernetes-intro', 'kubernetes-microprofile-config', 'kubernetes-microprofile-health']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: IBM Cloud tutorial
:page-seo-description: How to deploy microservices to IBM Cloud
:guide-author: Open Liberty
= Deploying microservices to IBM Cloud

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].
 
Explore how to push Docker images to a custom registry and run them inside of containers on IBM Cloud’s Kubernetes service.

:minikube-ip: 192.168.99.100
:kube: Kubernetes
:hashtag: #
:win: WINDOWS
:mac: MAC
:linux: LINUX
:system-api: http://[hostname]:[system-node-port]/system/properties
:inventory-api: http://[hostname]:[inventory-node-port]/inventory/systems


// =================================================================================================
// What is {kube}
// =================================================================================================

== Why use Kubernetes services in the cloud?

Single node {kube} clusters such as Minikube and Docker Desktop are great for testing your 
microservices locally, but ultimately you will want a system that can handle production workloads. 
Various clouds offer solutions for running your workloads in a {kube} cluster. Using a 
cloud-based infrastructure allows you to focus on developing your microservices rather than 
worrying about details that are related to the servers you deploy them to. Using cloud allows
you to easily scale your microservices and serve them in a high-availability setup.

// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

You will learn how to deploy two microservices in Open Liberty containers to a {kube}
cluster on IBM Cloud. You will use Helm to deploy these microservices using
Open Liberty Helm charts. Helm is a package manager for {kube}. It uses templates to
generate {kube} yaml files and then deploys and manages them as releases in your cluster.

IBM Cloud offers a hosted Kubernetes service that is called IBM Cloud Kubernetes Service (IKS). 
IKS is a service that is offered as part of IBM's public cloud offerings. It provides a 
hosted {kube} cluster that you can deploy your microservices to. You will use it 
with IBM Cloud Container Registry.

The two microservices you will deploy are called `system` and `inventory`. The `system` microservice
returns the JVM system properties of the running container and it returns the pod's name in the HTTP header
making replicas easy to distinguish from each other. The `inventory` microservice
adds the properties from the `system` microservice to the inventory. This demonstrates
how communication can be established between pods inside a cluster.

// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.

// =================================================================================================
// Creating a Kubernetes cluster on IBM Cloud
// =================================================================================================

== Creating a Kubernetes cluster on IBM Cloud

Before you can deploy your microservices, you must create a {kube} cluster.
To create a {kube} cluster, you need appropriate permission. Ensure that you have `Administrator` 
access to IBM Cloud Kubernetes Service. Navigate to the https://cloud.ibm.com/[IBM Cloud Dashboard^]. 
Then navigate to `Manage > Access (IAM) > Users > [Your Username] > Access Policies` and 
ensure that `Administrator` is listed as a policy for all resources in the account or for 
the Kubernetes service.

// =================================================================================================
// Installing command line tools for IBM Cloud
// =================================================================================================

=== Installing command line tools for IBM Cloud

Use the following command to download and install everything that you need to interact with IBM Cloud.
Running this script installs https://console.bluemix.net/docs/cli/index.html#overview[several tools^]
that are useful for interacting with IBM Cloud. It installs the `ibmcloud`, `kubectl`, `helm`,
and `curl` tools, which are needed to complete this guide.

****
[system]#*{linux} | {mac}*#

[role=command]
```
curl -sL https://ibm.biz/idt-installer | bash
```

[system]#*{win}*#

Open command prompt as an administrator and run the following command.

[role=command]
```
powershell -command "Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('http://ibm.biz/idt-win-installer')"
```
****

After the script is finished running, log in to IBM Cloud by using the `ibmcloud` command line. 
When you are prompted to select a region, choose `us-south`. Creating a free cluster is 
limited to specific regions, choosing `us-south` allows you to create a free cluster.

[role=command]
```
ibmcloud login
```

If you're logging in with organization credentials, you will need to pass in the `--sso` flag
to get a one time code for single sign-on. Follow the instructions that are given on the prompt and in
your web browser to complete the login process.

[role=command]
```
ibmcloud login --sso
```

// =================================================================================================
// Provisioning a cluster
// =================================================================================================

=== Provisioning a cluster

Use the following command to provision a cluster.

[role=command]
```
ibmcloud ks cluster-create --name guide-cluster
```

This command provisions a free cluster that expires in a month if you do not delete it.

[source, role="no_copy"]
----
The 'machine-type' flag was not specified. So a free cluster will be created.
Creating cluster...
OK
----

Check the current status of your cluster.

[role=command]
```
ibmcloud ks clusters
```

Wait until your cluster is in the `normal` state before proceeding. It will start off in the `deploying` state.

[source, role="no_copy"]
----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   deploying   4 minutes ago   1         Dallas     1.10.11_1536   default 
----

Next, it will transition to the `pending` state.

[source, role="no_copy"]
----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   pending     19 minutes ago   1         Dallas     1.10.11_1536   default 
----

Finally, it will transition to the `normal` state. It may take a while for IKS to prepare your cluster.

[source, role="no_copy"]
----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   normal      4 hours ago     1           Dallas     1.10.11_1536   default 
----


Once your cluster is ready, connect `kubectl` to the cluster.
****
[system]#*{linux} | {mac}*#

[role=command]
```
eval $(ibmcloud ks cluster-config --export guide-cluster)
```
[system]#*{win}*#

[role=command]
```
ibmcloud ks cluster-config --export guide-cluster > tmp-set-cluster.cmd
call tmp-set-cluster.cmd
del tmp-set-cluster.cmd
```
****

Verify that you're connected to the cluster by checking the cluster's nodes.

[role=command]
```
kubectl get nodes
```

[source, role="no_copy"]
----
NAME           STATUS    ROLES     AGE       VERSION
10.70.200.73   Ready     <none>    1h        v1.10.11+IKS
----

// =================================================================================================
// Deploying microservices to IBM Cloud Kubernetes Service (IKS)
// =================================================================================================

== Deploying microservices to IBM Cloud Kubernetes Service (IKS)

In this section, you will learn how to deploy two microservices in Open Liberty containers to a {kube}
cluster on IBM Cloud. You will build and containerize the `system` and `inventory` microservices,
push them to a Docker registry and then deploy them to your {kube} cluster. 

// =================================================================================================
// Building and containerizing the microservices
// =================================================================================================

=== Building and containerizing the microservices

The first step of deploying to {kube} is to build your microservices and containerize them with Docker.

The starting Java project, which you can find in the `start` directory, is a multi-module Maven
project. It's made up of the `system` and `inventory` microservices. Each microservice resides in its own directory,
`start/system` and `start/inventory`. Each of these directories also contains a Dockerfile, which is necessary
for building Docker images. If you're unfamiliar with Dockerfiles, check out the
https://openliberty.io/guides/docker.html[Using Docker containers to develop microservices^] guide.

If you're familiar with Maven and Docker, you might be tempted to run a Maven build first and then
use the `.war` file to build a Docker image. We've setup the projects such that this process is automated
as a part of a single Maven build. It's created by using the `dockerfile-maven` plug-in. The plug-in automatically
picks up the Dockerfile located in the same directory as its POM file and builds a Docker image from it.

****
[system]#*{win}*#

On the Docker Desktop General Setting page, ensure that the option `Expose daemon on 
tcp://localhost:2375 without TLS` is enabled. This configuration is required by the `dockerfile-maven` 
part of the build.

****

Navigate to the `start` directory and run the following command:

[role=command]
```
mvn package
```

The `package` goal automatically starts the `dockerfile-maven:build` goal. It runs during the
`package` phase. This goal builds a Docker image from the Dockerfile located in the same directory
as the POM file.

During the build, you'll see various Docker messages describing what images are being downloaded and
built. When the build finishes, run the following command to list all local Docker images:

[role=command]
```
docker images
```

Verify that the `system:1.0-SNAPSHOT` and `inventory:1.0-SNAPSHOT` images are listed among them, for example:

[source, role="no_copy"]
----
REPOSITORY                 TAG
system                     1.0-SNAPSHOT
inventory                  1.0-SNAPSHOT
open-liberty               latest
----

If you don't see the `system:1.0-SNAPSHOT` and `inventory:1.0-SNAPSHOT` images, then check the Maven
build log for any potential errors.

// =================================================================================================
// Pushing the images to a docker registry
// =================================================================================================

=== Pushing the images to a Docker registry

Pushing the images to a registry allow the cluster to create pods using your Docker images. 
Since it's a private repository, only users with access to your IBM Cloud account will have 
access to these images.

The registry you will use is called IBM Cloud Container Registry. The container registry
plugin was installed automatically while running the `idt-installer` earlier in this guide.
Use the container registry plugin to create a namespace for your container images.
The namespace must be unique within IBM Cloud for the region you selected, so choose something 
relevant that you'll remember for the duration of the guide.

[source, role="no_copy"]
```
ibmcloud cr namespace-add [your-namespace]
```

Use the plugin again to login to the Docker registry.

[role=command]
```
ibmcloud cr login
```

// Tagging images
Next, you need to tag your Docker images with the relevant data about your registry. 
Remember to substitute `[your-namespace]` for the namespace you previously created.

[source, role="no_copy"]
```
docker tag system:1.0-SNAPSHOT us.icr.io/[your-namespace]/system:1.0-SNAPSHOT
docker tag inventory:1.0-SNAPSHOT us.icr.io/[your-namespace]/inventory:1.0-SNAPSHOT
```

// Pushing images
Finally, push your images to the registry. Remember to substitute `[your-namespace]` for the 
namespace you previously created.

[source, role="no_copy"]
```
docker push us.icr.io/[your-namespace]/system:1.0-SNAPSHOT
docker push us.icr.io/[your-namespace]/inventory:1.0-SNAPSHOT
```


// =================================================================================================
// Deploying the microservices
// =================================================================================================

=== Deploying the microservices

https://helm.sh/[Helm^] is a package manager for {kube}. It allows you to create a package 
called a chart. You can install a chart on your cluster as a release and then manage the 
release using Helm.

// Setup Tiller for IKS
Set up role-based access control (RBAC) to give Helm's Tiller server admin access to your 
cluster. Deploy the service account and cluster role binding that is required for the Tiller.

[role=command]
```
kubectl apply -f https://raw.githubusercontent.com/IBM-Cloud/kube-samples/master/rbac/serviceaccount-tiller.yaml
```

[source, role="no_copy"]
----
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created
----

Next, install Tiller to your cluster. Specify that the Tiller should run under the service account that was created in the previous step.

[role=command]
```
helm init --service-account tiller
```

After the command completes, you will see output similar to the following.

[source, role="no_copy"]
----
$HELM_HOME has been configured at /Users/OpenLiberty/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!
----

All pods run under a service account. By default, your pod runs under the `default` service account for your namespace. Helm's Tiller server is running under the `tiller` service account. The `tiller` service account is bound to the cluster role `cluster-admin`. This role grants access to all resources in your cluster. Therefore, the Tiller server has access to all of your cluster's resources.

// Add repo
Add the `ibm-charts` repository to your local list of Helm repositories. Adding the repository allows you to use the `ibm-open-liberty` chart.

[role=command]
```
helm repo add ibm-charts https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
```

// Deploy to IKS
Use Helm to deploy the `system` microservice. Remember to substitute `[your-namespace]` for the namespace you created earlier in the guide.

****
[system]#*{linux} | {mac}*#

[source, role="no_copy"]
```
helm install --name system-app \
    --set image.repository=us.icr.io/[your-namespace]/system \
    --set image.tag=1.0-SNAPSHOT \
    --set image.pullSecret=default-us-icr-io \
    --set service.name=system-service \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty
```

[system]#*{win}*#

[source, role="no_copy"]
```
helm install --name system-app ^
    --set image.repository=us.icr.io/[your-namespace]/system ^
    --set image.tag=1.0-SNAPSHOT ^
    --set image.pullSecret=default-us-icr-io ^
    --set service.name=system-service ^
    --set service.port=9080 ^
    --set service.targetPort=9080 ^
    --set ssl.enabled=false ^
    ibm-charts/ibm-open-liberty
```

****

Use Helm to deploy the `inventory` microservice. Remember to substitute `[your-namespace]` for the namespace you created earlier in the guide.

****
[system]#*{linux} | {mac}*#

[source, role="no_copy"]
```
helm install --name inventory-app \
    --set image.repository=us.icr.io/[your-namespace]/inventory \
    --set image.tag=1.0-SNAPSHOT \
    --set image.pullSecret=default-us-icr-io \
    --set service.name=inventory-service \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty
```

[system]#*{win}*#

[source, role="no_copy"]
```
helm install --name inventory-app ^
    --set image.repository=us.icr.io/[your-namespace]/inventory ^
    --set image.tag=1.0-SNAPSHOT ^
    --set image.pullSecret=default-us-icr-io ^
    --set service.name=inventory-service ^
    --set service.port=9080 ^
    --set service.targetPort=9080 ^
    --set ssl.enabled=false ^
    ibm-charts/ibm-open-liberty
```

****


After running `helm install`, an output will be displayed providing instructions on how 
to access your deployed microservices. Ignore these instructions for now, you will learn 
how to access your microservices in the next section.

The `--name` flag specifies the release name, which must be unique. This is the name that 
Helm uses to identify this specific deployment of your chart. The following table gives 
an overview for each of the parameters specified using `--set`.

|===
| *Parameter* | *Description*
| `image.repository` | The name of your Docker image including registry/repository prefix
| `image.tag` | The tag for your Docker image
| `image.pullSecret` | The image pull secret
| `service.name` | The name of the service
| `service.port` | The port exposed by the service
| `service.targetPort` | The port exposed by the pod
| `ssl.enabled` | Specify if SSL is enabled
|===

=== Finding the microservice's IP address and ports

The service used to expose our deployments has a type of `NodePort`. This means you can 
access these services from outside of your cluster via a specific port. In this case,
since `nodePort` is not specified, the ports are randomized so you must obtain 
the ports before making requests to the services. You must also obtain the public IP address 
of our cluster. Note that there are other ways to expose your services such as using a 
`LoadBalancer` service type or using an `Ingress`. In production, you would most likely 
use an `Ingress`.

First, find the current context of your cluster.

[role=command]
```
kubectl config current-context
```

Take note of the context shown in the command's output.

[source, role="no_copy"]
----
guide-cluster
----

Then, substitute the context into the following command to get the public IP address of your cluster.

[role=command]
```
ibmcloud ks workers [current-context]
```

Take note of the `Public IP` in the command's output. This will be the hostname you 
substitue into commands later in this guide.

[source, role="no_copy"]
----
OK
ID                            Public IP       Private IP     Machine Type    State    Status   Zone    Version   
kube-hou02-pad15e5f9-w1       172.173.65.24   10.77.198.71   free            normal   Ready    hou02   1.10.11_1538*
----

Get the node port of the `system` microservice.

[role=command]
```
kubectl get service system-service -o jsonpath="{.spec.ports[0].nodePort}{'\n'}"
```

Get the node port of the `inventory` microservice.

[role=command]
```
kubectl get service inventory-service -o jsonpath="{.spec.ports[0].nodePort}{'\n'}"
```

Take note of the IP address and ports. They are required to make the HTTP requests.

=== Making requests to the microservices

To make a request to the `system` and `inventory` microservices,  `curl` or visit the 
following URLs to access your microservices, substituting the appropriate hostname and node ports:

- `{system-api}`
- `{inventory-api}/system-service`

The first URL returns system properties and the name of the pod in an HTTP header called `X-Pod-Name`.
To view the header, you can use the `-I` option in the `curl` when making a request to `{system-api}`.
The second URL adds properties from `system-service` to the inventory.

// =================================================================================================
// Testing microservices that are running on IBM Cloud
// =================================================================================================

== Testing microservices that are running on IBM Cloud

A few tests are included for you to test the basic functionality of the microservices. If a test failure
occurs, then you might have introduced a bug into the code. To run the tests, wait for all pods to be
in the ready state before proceeding further. The default properties that are defined in the `pom.xml` are:

[cols="15, 100", options="header"]
|===
| *Property*        | *Description*
| `cluster.ip`        | IP or hostname for your cluster
| `system.kube.service` | Name of the {kube} Service wrapping the `system` pods, `system-service` by default.
| `system.node.port`    | The NodePort of the {kube} Service `system-service`, 31000 by default.
| `inventory.node.port`    | The NodePort of the {kube} Service `inventory-service`, 32000 by default.
|===

Use the following command to run the integration tests against your cluster. Substitute 
`[ip-address]`, `[system-node-port]` and `[inventory-node-port]` with the appropriate values.

[source, role="no_copy"]
```
mvn verify -Ddockerfile.skip=true -Dcluster.ip=[ip-address] -Dsystem.node.port=[system-node-port] -Dinventory.node.port=[inventory-node-port]
```

The `dockerfile.skip` parameter is set to `true` in order to skip building a new Docker image.

If the tests pass, you'll see an output similar to the following for each service respectively:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.673 sec - in it.io.openliberty.guides.system.SystemEndpointTest

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.222 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

=== Deploying new version of system microservice

Optionally, you might want to learn how to redeploy a microservice. In this section, you 
will bump the version of the `system` microservice to `2.0-SNAPSHOT` and redeploy
the new version of the microservice. You can re-deploy a microservice using Helm to upgrade 
the release.

The tag for the Docker image is dependent on the version specified in the pom.xml file. 
Use the following Maven command to bump the version of the microservice to `2.0-SNAPSHOT`.

[role=command]
```
mvn versions:set -DnewVersion=2.0-SNAPSHOT
```

Use Maven to repackage your microservice and build the new version of the Docker container.
[role=command]
```
mvn package
```

Since you built a new image, it will have to be pushed to the repository again.

// Tagging images
Tag your Docker image with the relevant data about your registry.

[source, role="no_copy"]
```
docker tag system:2.0-SNAPSHOT us.icr.io/[your-namespace]/system:2.0-SNAPSHOT
```

// Pushing images
Push your image to the registry.

[role=command]
```
docker push us.icr.io/[your-namespace]/system:2.0-SNAPSHOT
```

Use Helm to re-deploy the `system` microservice.

****
[system]#*{linux} | {mac}*#

[source, role="no_copy"]
```
helm upgrade \
    --set image.repository=us.icr.io/[your-namespace]/system \
    --set image.tag=2.0-SNAPSHOT \
    --set image.pullSecret=default-us-icr-io \
    --set service.name=system-service \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    system-app ibm-charts/ibm-open-liberty
```

[system]#*{win}*#

[source, role="no_copy"]
```
helm upgrade ^
    --set image.repository=us.icr.io/[your-namespace]/system ^
    --set image.tag=2.0-SNAPSHOT ^
    --set image.pullSecret=default-us-icr-io ^
    --set service.name=system-service ^
    --set service.port=9080 ^
    --set service.targetPort=9080 ^
    --set ssl.enabled=false ^
    system-app ibm-charts/ibm-open-liberty
```

****

Use the following command to find the name of the pod running the `system` microservice.

[role=command]
```
kubectl get pods
```

[source, role="no_copy"]
----
NAME                                        READY     STATUS    RESTARTS   AGE
inventory-app-ibm-open-l-5c586b9cfc-h5zmg   1/1       Running   0          23s
system-app-ibm-open-libe-84976bccfb-r22lj   1/1       Running   0          2m15sm
----

Observe that in this case the `system` microservice is running in the pod called `system-app-ibm-open-libe-84976bccfb-r22lj`. Substitute the name of your pod into the following command to see more details about the pod.

[source, role="no_copy"]
```
kubectl describe pod [pod-name]
```

View the events at the bottom of the command's output. Observe that the pod is using the new Docker image `system:2.0-SNAPSHOT`.

[source, role="no_copy"]
----
Events:
  Type     Reason     Age                From                   Message
  ----     ------     ----               ----                   -------
  Normal   Scheduled  47s                default-scheduler      Successfully assigned default/system-app-ibm-open-libe-84976bccfb-r22lj 172.173.65.24
  Normal   Pulling    47s                kubelet, 172.173.65.24  pulling image "registry.ng.bluemix.net/[your-namespace/system:2.0-SNAPSHOT"
  Normal   Pulled     40s                kubelet, 172.173.65.24  Successfully pulled image "registry.ng.bluemix.net/[your-namespace]/system:2.0-SNAPSHOT"
  Normal   Created    40s                kubelet, 172.173.65.24  Created container
  Normal   Started    39s                kubelet, 172.173.65.24  Started containerr
----

// =================================================================================================
// Tear Down
// =================================================================================================

== Tearing down the environment

When you no longer need your deployed microservices, you can delete them with the following Helm commands:

[role=command]
```
helm delete --purge system-app
helm delete --purge inventory-app
```

Uninstall Tiller from your cluster by running the following Helm command.

[role=command]
```
helm reset
```

Logout of your Docker registry.

[role=command]
```
docker logout us-south.icr.io
```

Remove your IKS cluster.

[role=command]
```
ibmcloud ks cluster-rm guide-cluster
```

Logout of the `ibmcloud` command line tool.

[role=command]
```
ibmcloud logout
```


== Deploying to IBM Cloud Private

Some situations may require you to manage your own infrastructure, such as if you want 
to deploy on-premises. If this describes your needs, then private clouds may be a more 
suitable solution for you.

https://www.ibm.com/cloud/private[IBM Cloud Private^] (ICP) is a {kube} platform. A private 
cloud may be a more attractive option to those who must run their services on 
infrastructure that is controlled by them. While the operations team will still need to 
maintain this infrastructure, a private cloud still provides benefit to developers so 
they don't need to think about infrastructure. {kube} acts as an abstraction of the 
infrastructure so the developers can request what they need and it is the responsibility 
of the infrastructure's maintainers to provide the necessary resources.

Deploying microservices to ICP is a similar process as deploying to IKS. The main differences 
that you will notice are in the setup process and how you tag your Docker images.

To obtain an ICP instance, see the https://www.ibm.com/cloud/private[IBM Cloud Private^] 
website. To set up your local environment, from the ICP Dashboard navigate to the 
`Command Line Tools > Cloud Private CLI` page from the menu and follow the instructions 
to set up each CLI tool. Unlike IKS, you do not need to run `helm init` or deploy the 
cluster role binding and service account to your cluster. This is because ICP has Helm's 
Tiller setup for you out of the box. To connect your local command line tools to the ICP 
instance, use https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.1.0/manage_cluster/cli_commands.html#login[cloudctl login^].

When you tag a Docker image, you must tag the image with the registry as a prefix to your 
image name. This prefix is how Docker knows which registry to push your images to. For 
example, assume your ICP instance's Docker registry is `mycluster.icp:8500`. To tag your 
image, you must prefix the image name with the registry and namespace. Let's say you want 
to push your image to a repository in the default namespace, then you would tag your `system`
microservice's image `mycluster.icp:8500/default/system`. This tag specifies `mycluster.icp:8500` 
as the Docker registry to push to and it specifies `default` as the namespace your image's 
repository will reside in.

You can learn more about deploying microservices to ICP by following an 
https://www.ibm.com/cloud/garage/demo/try-private-cloud-install-an-app[interactive guided demo^].

// =================================================================================================
// finish
// =================================================================================================

== Great work! You're done!

You have just deployed two microservices to IBM Cloud. You have learned to use Helm to install your microservices
on a {kube} cluster using the Open Liberty helm chart.

// Multipane
include::{common-includes}/attribution.adoc[subs="attributes"]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
