// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: ibm-cloud-intro
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2018-10-05
:page-description: Explore how to deploy microservices to IBM Cloud Private and manage your cluster.
:page-tags: ['microservices', 'Kubernetes', 'Docker', 'containers', 'kubectl', 'ICP', 'IBM Cloud Private']
:page-permalink: /guides/{projectid}
:page-related-guides: ['kubernetes-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: IBM Cloud tutorial
:page-seo-description: How to deploy microservices to IBM Cloud
= Deploying microservices to IBM Cloud

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Deploy microservices in Open Liberty Docker containers to IBM Cloud.

:minikube-ip: 192.168.99.100
:kube: Kubernetes
:hashtag: #
:win: WINDOWS
:mac: MAC
:linux: LINUX
:name-api: http://[hostname]:31000/api/name
:ping-api: http://[hostname]:32000/api/ping


// =================================================================================================
// What is {kube}
// =================================================================================================

== IBM Cloud

Single node {kube} clusters such as Minikube and Docker Desktop are great for testing your microservices locally. In production, you'll want to use something more robust. IBM Cloud offers solutions for running your workloads in a Kubernetes cluster. Using IBM Cloud allows you to focus on developing your microservices rather than worrying about details related to the servers you'll deploy them to. 

=== What is IBM Cloud Private (ICP)?

IBM Cloud Private is a {kube} platform that provides an on-premises cloud solution. It has many useful features for your cloud needs. The main feature it provides is a {kube} cluster. It works just like any {kube} cluster and can be manipulated with `kubectl`. Another useful feature it provides is a private docker registry so that you don't need to use something like https://hub.docker.com/[Docker Hub]. Some other capabilities it provides include a dashboard and a web interface to deploy helm charts.

=== What is IBM Cloud Kubernetes Service (IKS)?

IKS is a service offered as part of IBM's public cloud offerings. It provides a managed {kube} cluster that you may deploy your microservices to. You will use it in conjunction with IBM Cloud Container Registry.

// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

You will learn how to deploy two microservices in Open Liberty containers to a {kube}
cluster on IBM Cloud. You will use `helm` to deploy these microservices using IBM's
Open Liberty Helm charts.

The two microservices you'll deploy are called `name` and `ping`. The `name` microservice
displays a brief greeting and the name of the
container it's running in. This message makes it easy to differentiate it from its other replicas. The `ping` microservice
pings the {kube} Service that encapsulates the `name` pods. This communication demonstrates
how communication can be established between pods inside a cluster.

// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisites

First, you will need Docker to build your containers, refer to the https://docs.docker.com/install/[official Docker documentation] to install Docker.

You will also need to install the https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl] cli tool.

Finally, you'll need to have access to an IBM Cloud Private instance that you may use to follow the guide. This is only necessary if you
are following the ICP instructions. You do not need an ICP instance to follow the IKS instructions.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.


// =================================================================================================
// Deploying microservices to IBM Cloud Private (ICP)
// =================================================================================================

== Deploying microservices to IBM Cloud Private (ICP)

=== Installing cloudctl

1. First, login and navigate to your ICP dashboard.
2. Click the icon located at the upper left of the page to expand the menu.
3. Click `Command Line Tools > Cloud Private CLI` to navigate to the `IBM Cloud Private CLI` page.
4. Click `Install IBM Cloud Private CLI and plug-ins` and follow the instructions to download the `cloudctl` tool.

****
[system]#*{linux} | {mac}*#

Move and rename the downloaded file to `/usr/local/bin/cloudctl` then make it executable.

[role=command]
```
sudo mv `ls cloudctl-*` /usr/local/bin/cloudctl
sudo chmod +x /usr/local/bin/cloudctl
```

[system]#*{win}*#

Create a directory called `cloudctl-bin` under your user directory and add it to your `PATH` environment variable.

[role=command]
```
mkdir %systemdrive%%userprofile%\cloudctl-bin
set PATH=%PATH%;%systemdrive%%userprofile%\cloudctl-bin
```

Next, move the file you downloaded into the `cloudctl-bin` directory and rename the file to `cloudctl.exe`.
****

=== Installing helm

Click `Install Helm` on the same page where you downloaded `cloudctl`. Follow the instructions to download `helm`.

****
[system]#*{linux} | {mac}*#

Use the following commands to extract the archive and move the helm binary to `/usr/local/bin/helm` and then make it executable.

[role=command]
```
mkdir helm
tar -zxf helm-* -C helm/
sudo mv helm/`ls helm`/helm /usr/local/bin/helm
sudo chmod +x /usr/local/bin/helm
```

[system]#*{win}*#

Create a directory called `helm-cli` under your user directory and extract the contents of the file
you downloaded to this directory. Use the following commands to add `helm` to your path.

Create a directory called `helm-cli` under your user directory and add it to your `PATH` environment variable.

[role=command]
```
mkdir %systemdrive%%userprofile%\helm-cli\windows-amd64
set PATH=%PATH%;%systemdrive%%userprofile%\helm-cli\windows-amd64
```

Next, extract the file you downloaded into the `helm-cli` directory.
****

=== Connecting kubectl and helm to ICP

Connect the `kubectl` cli tool to your cluster by logging in to the cluster, replace `[hostname]` and `[port]` as appropriate with the values for your ICP instance.

[role=command]
```
cloudctl login -a https://[hostname]:[port]  --skip-ssl-validation
```

When prompted, enter your user name and password. Then, select the cluster account. Finally, ensure to select the `default` namespace.

----
Username> enter_your_username	

Password> enter_your_password
Authenticating...
OK

Select an account:
1. mycluster Account (id-mycluster-account)
Enter a number> 1
Targeted account mycluster Account (id-mycluster-account)

Select a namespace:
1. cert-manager
2. default
3. ibmcom
4. istio-system
5. kube-public
6. kube-system
7. platform
8. services
Enter a number> 2
Targeted namespace default

Configuring kubectl ...
Property "clusters.mycluster" unset.
Property "users.mycluster-user" unset.
Property "contexts.mycluster-context" unset.
Cluster "mycluster" set.
User "mycluster-user" set.
Context "mycluster-context" created.
Switched to context "mycluster-context".
OK

Configuring helm: ~/.helm
OK
----

Verify that you're connected to the cluster by checking the cluster's nodes.

[role=command]
```
kubectl get nodes
```

----
NAME           STATUS    ROLES                          AGE       VERSION
192.168.0.15   Ready     worker                         10d       v1.11.1+icp-ee
192.168.0.10   Ready     worker                         10d       v1.11.1+icp-ee
192.168.0.5    Ready     etcd,management,master,proxy   10d       v1.11.1+icp-ee
----

:use-icp: true
include::partials/build-and-containerizing.adoc[]

include::partials/pushing-images.adoc[]

include::partials/deploying.adoc[]

include::partials/making-requests.adoc[]

include::partials/testing.adoc[]

include::partials/tearing-down.adoc[]

include::partials/finish.adoc[]

== Deploying microservices to IBM Cloud Kubernetes Service (IKS)

=== Installing command line tools for IBM Cloud

Use the following command to download and install everything you will need to interact with IBM Cloud.
Running this script will install https://console.bluemix.net/docs/cli/index.html#overview[several tools]
that will be useful for interacting with IBM Cloud. It will install the `ibmcloud`, `kubectl`, `helm`,
and `curl` tools which are needed to complete this guide.

****
[system]#*{linux} | {mac}*#

[role=command]
```
curl -sL https://ibm.biz/idt-installer | bash
```

[system]#*{win}*#

Open PowerShell as an administrator and run the following command.

[role=command]
```
Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('http://ibm.biz/idt-win-installer')
```
****

Once the script has finished running, login with the command line to IBM Cloud.

[role=command]
```
ibmcloud login
```

If you're logging in with organization credentials, you may need to pass in the `--sso` flag
to get a one time code for single sign-on. Follow the instructions given on the prompt and in
your web browser to complete the login process.

[role=command]
```
ibmcloud login --sso
```

=== Provisioning a cluster

Use the following command to provision a cluster.

// ```
// ibmcloud ks cluster-create \
//     --zone dal10 \
//     --machine-type b2c.4x16 \
//     --hardware <shared_or_dedicated> \
//     --public-vlan <public_VLAN_ID> \
//     --private-vlan <private_VLAN_ID> \
//     --workers 3 \
//     --name <cluster_name> \
//     --kube-version <major.minor.patch>
// ```

[role=command]
```
ibmcloud ks cluster-create --name guide-cluster
```

This command provisions a free cluster that will expire in a month if you do not delete it.

----
The 'machine-type' flag was not specified. So a free cluster will be created.
Creating cluster...
OK
----

Check the current status of your cluster.

[role=command]
```
ibmcloud ks clusters
```

----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   deploying   4 minutes ago   1         Dallas     1.10.11_1536   default 
----

----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   pending     19 minutes ago   1         Dallas     1.10.11_1536   default 
----

Wait until the `State` of your cluster is `normal` before proceeding with the guide. This may take a while for IKS to prepare your cluster.

----
Name            ID                                 State       Created         Workers   Location   Version        Resource Group Name   
guide-cluster   d1229f539ee902ca91g6d187c2dxy5s3   normal      4 hours ago     1           Dallas     1.10.11_1536   default 
----


Once your cluster is ready, connect `kubectl` to the cluster.
****
[system]#*{linux} | {mac}*#

```
eval $(ibmcloud ks cluster-config --export guide-cluster)
```
[system]#*{win}*#

```
ibmcloud ks cluster-config --export guide-cluster > tmp-set-cluster.cmd
call tmp-set-cluster.cmd
del tmp-set-cluster.cmd
```
****

Verify that you're connected to the cluster by checking the cluster's nodes.

[role=command]
```
kubectl get nodes
```

----
NAME           STATUS    ROLES     AGE       VERSION
10.70.200.73   Ready     <none>    1h        v1.10.11+IKS
----

:!use-icp:
:use-iks: true
include::partials/build-and-containerizing.adoc[]

include::partials/pushing-images.adoc[]

include::partials/deploying.adoc[]

include::partials/making-requests.adoc[]

include::partials/testing.adoc[]

include::partials/tearing-down.adoc[]

include::partials/finish.adoc[]

// Include the below from the guides-common repo to tell users how they can contribute to the guide
include::{common-includes}/finish.adoc[]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
